version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: mcp-registry-meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  meili_data:
    driver: local