# x: print each command
set -x
cd python-mcp

# initialize the project if pyproject.toml does not exist
if [ ! -f pyproject.toml ]; then
  uv init
fi

# delete old lock file to ensure a clean installation
rm -f uv.lock

# add dependencies one by one
uv add mcp-server-fetch
uv add mcp-server-make
uv add mcp-server-sqlite
uv add mcp-tinybird
uv add mcp-server-aidd
uv add mcp-server-tree-sitter
uv add docker-mcp
uv add awslabs.nova-canvas-mcp-server
uv add mcp-solver
uv add mcp-rememberizer-vectordb
uv add mcp-server-rememberizer
uv add mcp-server-sentry
uv add mcp-server-perplexity
uv add qanon_mcp
uv add mcp-server-git
uv add mcp-server-time
uv add nautobot-mcp
uv add azure-fhir-mcp-server
uv add aptos
uv add wegene
uv add fulcra-context-mcp
uv add garth-mcp-server
uv add oura
uv add whoop
uv add videodb-director-mcp
uv add mcp-server-garmincn
uv add thirdweb-mcp
uv add zillow
uv add openai-agents
uv add unichat-mcp-server
uv add magg
uv add aipolabs-mcp
uv add rapidapi
uv add llm-gateway
uv add mcptoolkit
uv add gateway
uv add acp-mcp-server
uv add union
uv add jentic
uv add mcp-superiorapis
uv add llm_bridge_mcp
uv add photoshop
uv add speckle
uv add processing
uv add mureka-mcp
uv add blender-mcp
uv add heygen-mcp
uv add grasshopper-mcp
uv add mcp-server-ancestry
uv add nasa-mcp
uv add comfyui
uv add comfy-mcp-server
uv add wikipedia
uv add mcp-sonic-pi
uv add ableton-mcp
uv add apple-books-mcp
uv add sketchfab-mcp
uv add trakt
uv add biomcp-python
uv add midjourney
uv add penpot-mcp
uv add undetected-chromedriver
uv add web-scraper
uv add mcp-pyautogui-server
uv add scrapling-fetch-mcp
uv add mcp-playwright-scraper
uv add mcp_server_browser_use
uv add mcp-rquest
uv add browser-use
uv add browser-use-mcp-server
uv add notte-browser
uv add computer-control-mcp
uv add skyvern
uv add browser-use-mcp
uv add mcp-browser-use
uv add twitter
uv add web-crawler
uv add mcp-server-chatgpt-app
uv add gcp-mcp
uv add alibabacloud-mcp-server
uv add azure
uv add yourware-mcp
uv add gcp-mcp-server
uv add aws-ec2-pricing
uv add linode-mcp
uv add aws-lambda
uv add awslabs.cdk-mcp-server
uv add modal
uv add mcp-python-interpreter
uv add docker-executor
uv add mcp-python
uv add python-local
uv add jupyter_mcp_server
uv add serena
uv add code-analysis
uv add mcp-perplexity
uv add deepview-mcp
uv add mcp-server-code-assist
uv add claude-code
uv add codechecker
uv add codeforces
uv add aider
uv add strands-agents
uv add a2amcp-sdk
uv add nuanced
uv add python-code-analyzer
uv add compiler-explorer-mcp
uv add server
uv add command-line
uv add mcp-shell-server
uv add wcgw
uv add terminal-controller
uv add cli-mcp-server
uv add shell-mcp-server
uv add homebrew
uv add perplexity-advanced-mcp
uv add phone-mcp
uv add mcp-windows
uv add mcp-server-shell
uv add mcp-server-macos-defaults
uv add hyprland
uv add cua-mcp-server
uv add macos-notification-mcp
uv add mcp-kubernetes-server
uv add gmail-mcp
uv add mcp-email-server
uv add didlogic_mcp
uv add mcp-wechat-moments
uv add warpcast
uv add quickchat-ai-mcp
uv add keep-mcp
uv add google-workspace
uv add signal
uv add weibo
uv add linkedin-mcp
uv add telegram
uv add onesignal
uv add mcp-server-monday
uv add mcp-telegram
uv add mcp-simple-openai-assistant
uv add mcp-gotify
uv add voice-mcp
uv add microsoft-teams
uv add mac-messages-mcp
uv add mcp-feishu-proj
uv add dingtalk
uv add mcp-google-contacts-server
uv add x-twitter-mcp
uv add mcp-fleur
uv add wecom-bot-mcp-server
uv add x-mcp
uv add migadu-mcp
uv add teamspeak-mcp
uv add mcp-server-email
uv add hubspot
uv add mcp-salesforce-connector
uv add mcp-server-port
uv add mcp-server-starrocks
uv add pyodbc
uv add airtable
uv add lancedb
uv add mcp-server-motherduck
uv add adb-mysql-mcp-server
uv add mcp-timeplus
uv add mssql-mcp-server
uv add mcp_snowflake_server
uv add mcp-server-iris
uv add greptimedb-mcp-server
uv add database-mcp
uv add clickhouse-mcp-server
uv add materialize
uv add oracledb-mcp-server
uv add dolphindb
uv add appwrite
uv add mcp-server-mariadb
uv add opensearch
uv add apache-iotdb
uv add memgraph
uv add postgres-mcp
uv add dblp
uv add mochow-mcp-server
uv add chromadb
uv add mcp-dbutils
uv add clickhouse
uv add mysqldb-mcp-server
uv add zaturn
uv add mcp-doris
uv add ydb-mcp
uv add starrocks
uv add influxdb
uv add toolfront
uv add sqlite-explorer
uv add mssql_mcp_server
uv add mcp-db-navigator
uv add supabase
uv add mcp-server-bigquery
uv add hologres-mcp-server
uv add singlestore-mcp-server
uv add mcp-server-aact
uv add age-mcp-server
uv add nebulagraph-mcp-server
uv add mcp-trino-python
uv add mcp-neo4j-cypher
uv add oracle-mcp-server
uv add google-analytics-mcp
uv add explorium-mcp-server
uv add mcp-server-openmetadata
uv add apache-gravitino
uv add mcp-server-opendal
uv add bitable-mcp
uv add airflow-mcp-server
uv add mcp-server-apache-airflow
uv add datahub
uv add dune-analytics
uv add kestra
uv add prefect-mcp-server
uv add databutton-app-mcp
uv add mcp-google-sheets
uv add apache-iceberg
uv add dbt-mcp
uv add mcp_cube_server
uv add agentmode
uv add eunomia
uv add databricks
uv add metabase
uv add mcp-server-alteryx
uv add mcp-pinot-server
uv add odmcp
uv add world-bank-data
uv add iceberg-mcp
uv add graphql-explorer
uv add earthdata_mcp_server
uv add phalcon
uv add argocd
uv add mcp-toolbox
uv add python-toolbox
uv add dap-mcp
uv add llm-context
uv add freecad-mcp
uv add kubectl-mcp-tool
uv add paelladoc
uv add maya
uv add mcp-server-llmling
uv add mcpandroidbuild
uv add agentcraft_mcp
uv add mcp-azure-devops
uv add mcpdoc
uv add hanzo-mcp
uv add devdocs
uv add code2prompt
uv add nuke
uv add tokenscope
uv add mcp-nixos
uv add log-analyzer-mcp
uv add office-word-mcp-server
uv add officemcp
uv add code2flow
uv add jnews-mcp-server
uv add zen
uv add devhub-cms-mcp
uv add bitrise
uv add office-powerpoint-mcp-server
uv add mcp-server-restart
uv add mcp-sys-bridge
uv add docker-compose
uv add duckdb-mcp-server
uv add mcp-server-duckdb
uv add dataset-viewer
uv add mlflow
uv add mcp-wolfram-alpha
uv add biomart
uv add linear-regression
uv add mcp-vcd
uv add graphistry
uv add opengenes-mcp
uv add kaggle-mcp
uv add chronulus-mcp
uv add sympy
uv add kodit
uv add storm
uv add numpy
uv add mcp-excel-server
uv add tecton
uv add spark-optimizer
uv add vizro-mcp
uv add jupyter_earth_mcp_server
uv add pbixray
uv add data-explorer
uv add mlcbakery
uv add docling
uv add mindsdb
uv add hex
uv add zenml
uv add superset
uv add graphrag
uv add mcp2serial
uv add mcp-server-home-assistant
uv add mcp-server-ida
uv add mcp2tcp
uv add frida-mcp
uv add droidmind
uv add file-converter
uv add pdf-manipulation
uv add excel
uv add notes
uv add google-drive
uv add mcp_pdf_forms
uv add putio-mcp-server
uv add apple-notes-mcp
uv add ffmpeg-mcp
uv add excel-mcp-server
uv add json-canvas
uv add filesys
uv add file-finder
uv add spire.xls
uv add mcp-tree-explorer
uv add ledger
uv add sticky-notes
uv add mcp-obsidian
uv add mcp-text-editor
uv add polymarket
uv add artemis-mcp
uv add akshare_mcp
uv add mbbank-mcp
uv add akshare-one-mcp
uv add fewsats-mcp
uv add binance
uv add solana
uv add ramp
uv add ledger-cli
uv add schwab
uv add awslabs.cost-analysis-mcp-server
uv add ton-mcp-server
uv add stripe
uv add yfmcp
uv add mcp-server-twelve-data
uv add gp
uv add kospi-kosdaq-stock-server
uv add setu_mcp_kyc
uv add etf-flow-mcp
uv add deriv
uv add square
uv add polygon.io
uv add octagon-vc-agents
uv add futu-api
uv add freqtrade
uv add extend_ai_toolkit
uv add setu_mcp_upi_deeplinks
uv add quantconnect-mcp
uv add sec-edgar
uv add ynab
uv add bonk-mcp
uv add finance-tools-mcp
uv add investor-agent
uv add financial-datasets
uv add yahoo-finance
uv add openregister
uv add alphavantage
uv add mcp-chess
uv add opendota
uv add sourcesage
uv add zotero-mcp
uv add mcp-pinecone
uv add wikidata
uv add readwise
uv add mcp-codebase-insight
uv add mcp-server-obsidian-omnisearch
uv add memory-plus
uv add chroma-mcp-server
uv add memory-journal-mcp-server
uv add memos-mcp-server
uv add logseq-mcp
uv add mcp-server-vikingdb
uv add mcp-outline
uv add memory-mcp-server
uv add txtai
uv add memory-manager
uv add awslabs.bedrock-kb-retrieval-mcp-server
uv add mcp-server-logseq
uv add memory_mcp
uv add bear
uv add cognee
uv add mindmap-mcp-server
uv add mcp-server-qdrant
uv add context-portal-mcp
uv add obsidian-api-mcp-server
uv add basic-memory
uv add mcpunk
uv add graphiti
uv add openstreetmap
uv add mcp-myip
uv add weather
uv add world-time
uv add aemet_mcp
uv add weather-api
uv add mcp_weather_server
uv add geo
uv add jweather-mcp-server
uv add knmi-weather-mcp
uv add gis-mcp
uv add meta-ads-mcp
uv add mcp-metricool
uv add mailchimp
uv add google-ads
uv add linkedin
uv add mackerel
uv add mcp-ntopng
uv add prometheus
uv add logstash
uv add mcp-sentry
uv add system-info
uv add isitdown
uv add observe
uv add mcp-server-aliyun-observability
uv add mcp-sentry-custom
uv add logfire-mcp
uv add gpt-researcher
uv add oxylabs-mcp
uv add searxng-simple-mcp
uv add backlinks-mcp
uv add crawlab
uv add pubmedmcp
uv add ebay
uv add serper-mcp-server
uv add paperpal
uv add vectara-mcp
uv add youtube-dlp-server
uv add searxng-search
uv add reference-mcp
uv add pdfsearch
uv add mcp-hn
uv add pubmed-mcp-server
uv add higress-ai-search-mcp-server
uv add mcp-server-webcrawl
uv add pdf-processor
uv add mcp-search-linkup
uv add mcp-google-cse
uv add gnews
uv add mcp-simple-pubmed
uv add mcp-server-pacman
uv add opensearch-mcp-server
uv add web-browser-mcp-server
uv add mcp-tavily
uv add mcp-server-reddit
uv add mcp-simple-arxiv
uv add arxiv-mcp-server
uv add ddg-mcp
uv add imdb
uv add ddg-mcp-server
uv add bing-webmaster-tools
uv add pubmed
uv add cryo-mcp
uv add twikit
uv add agora-mcp
uv add mcp-server-docy
uv add perplexity-mcp
uv add outscraper
uv add mcp-grep
uv add mcp-openapi
uv add web-search
uv add google-custom-search
uv add openai-websearch-mcp
uv add kv-extractor-mcp-server
uv add reddit-mcp
uv add domain-tools
uv add baidu-mcp-server
uv add box
uv add rapidocr-mcp
uv add openapi_mcp_server
uv add arxiv
uv add duckduckgo-mcp-server
uv add mcp-server-everything-search
uv add docs2prompt
uv add naver-search
uv add meilisearch
uv add gemini-deepsearch-mcp
uv add youtube-transcript-downloader
uv add mcp-searxng
uv add mitmproxy
uv add virustotal
uv add mcp-nvd
uv add argus
uv add crypto
uv add defectdojo-mcp
uv add zoomeye
uv add zeek
uv add plexus
uv add illumio
uv add lanalyzer
uv add bloodhound
uv add 1password
uv add memprocfs
uv add mcp-panther
uv add mythic
uv add cve-search
uv add chess.com-api
uv add fpl-mcp
uv add nba-stats
uv add strava
uv add nba-player-stats
uv add servicenow
uv add shortcut
uv add mcp-atlassian
uv add jira
uv add clickup
uv add hh-jira-mcp-server
uv add freshdesk-mcp
uv add zendesk
uv add freshservice-mcp
uv add rootly-mcp-server
uv add devrev-mcp
uv add pagerduty_mcp_server
uv add pearl
uv add personal-jira-mcp
uv add taiga
uv add linear
uv add testrail-mcp
uv add hkopenai.hk_transportation_mcp_server
uv add google-flights
uv add caltrain-mcp
uv add flights-mcp
uv add git-pr
uv add git-mcp
uv add github-chat-mcp
uv add mcp-github-projects
uv add pygithub
uv add mcp-server-diff-python
uv add bitbucket
uv add elevenlabs-mcp
uv add time-converter
uv add mcp-serverman
uv add hirebase-mcp
uv add image-processor
uv add minimax-mcp
uv add rqbit-mcp
uv add chatterbox-tts
uv add mcp-pandoc
uv add second-opinion
uv add ask-human-mcp
uv add pymol
uv add markitdown
uv add locust
uv add ollama
uv add cheerlights
uv add speech-mcp
uv add daisys-mcp
uv add elevenlabs
uv add fibery-mcp-server
uv add think
uv add email-validator
uv add whissle
uv add video-editor-mcp
uv add mcp-applemusic
uv add random-number-generator
uv add rabbitmq
uv add claude-api
uv add kokoro-tts
uv add deepseek
uv add harvest
uv add uniprot
uv add mcp-toolhouse
uv add soundcloud-downloader
uv add blender
uv add personal-assistant
uv add mcp-server-calculator
uv add sandbox-fusion
uv add jexchange-mcp-server
uv add mcp-gsuite
uv add govee
uv add haiguitang-mcp
uv add toolhouse
uv add resemble
uv add mcp-google-docs
uv add screenshot
uv add ffmpeg
uv add taskmate
uv add time-mcp-local
uv add cort-mcp
uv add mcp-server-memos
uv add kroger-mcp
uv add awslabs.aws-documentation-mcp-server
uv add registry
uv add allvoicelab-mcp
uv add think_mcp
uv add langchain-mcp
uv add bilibili
uv add mcp-server-replicate
uv add openai
uv add mcp-simple-timeserver
uv add mcp-think-tool
uv add spotify-mcp
uv add neodb
uv add mcp-ankiconnect
uv add revit-mcp
uv add creator
uv add sequential-story
uv add flowise
uv add casual-mcp-server-words
uv add mcp-slicer
uv add replicate
uv add sudoku-solver
uv add tuya-mcp-server
uv add owl-mcp
uv add ttaat
uv add mindm
uv add mcp-llms-txt
uv add tripo-mcp
uv add mcp-ollama
uv add dust
uv add promptlab
uv add mcp-server
uv add hashnode
uv add mcp-timeserver
uv add reaper
uv add dicom
uv add videocapture
uv add odoo-mcp-improved
uv add ygg-torrent-mcp
uv add ntlk-mcp-002
uv add mcp-server-mas-sequential-thinking
uv add mcp-openapi-proxy
uv add interactive-feedback
uv add a2a-mcp-server
uv add anki-mcp
uv add atla
uv add claude-todo-emulator
uv add mcp-sleep
uv add spotify
uv add mistral-ocr
uv add sherlock-mcp
uv add time
uv add mcp-datetime
uv add needle
uv add open-deep-research
uv add postal-mcp
uv add mcp-gigapi
uv add devbrain
uv add scanpy
uv add frankfurtermcp
uv add binance-futures-mcp
uv add ip2location.io
uv add urldna
uv add authentik-mcp
uv add goodday-mcp
uv add mcp-server-screeny
uv add random-number-mcp
uv add storyblok
uv add orly-mcp
uv add train_12306
uv add mcp-12306
uv add mcp-google-analytics

echo "All Python dependencies have been installed successfully."
