/**
 * Featured MCP Servers Configuration
 *
 * Maintained by toolsdk.ai
 * Contains toolsdk.ai's officially recommended featured mcp servers
 */

export default [
	"@kevinwatt/mcp-webhook",
	"@mzxrai/mcp-openai",
	"@kazuph/mcp-gmail-gas",
	"@tsmztech/mcp-server-salesforce",
	"@modelcontextprotocol/server-slack",
	"@taazkareem/clickup-mcp-server",
	"@isaacphi/mcp-gdrive",
	"@kevinwatt/mysql-mcp",
	"@modelcontextprotocol/server-github",
	"@cristip73/mcp-server-asana",
	"@enescinar/twitter-mcp",
	"@toolsdk.ai/mcp-server-google-analytics",
	"@floriscornel/teams-mcp",
	"@pinkpixel/mindbridge",
	"@toolsdk.ai/tavily-mcp",
	"@notionhq/notion-mcp-server",
	"@niledatabase/nile-mcp-server",
	"@toolsdk.ai/mcp-send-email",
	"@pinkpixel/mindbridge",
	"exa-mcp-server",
	"hyperbrowser-mcp",
	"linkedin-mcp-runner",
	"deepl-mcp-server",
	// '@cocal/google-calendar-mcp',
	// '@Tisik79/MCP-Facebook',
	// '@lkm1developer/hubspot-mcp-server',
	// '@amir-bengherbi/shopify-mcp-server',
	// '@mattcoatsworth/Klaviyo-MCP-Server-4-15',
	// '@alfork/qbconductor-mcp-server',
	// '@mattcoatsworth/mailchip-mcp-server',
	// '@koundinya/zd-mcp-server',
	// '@pnizer/wweb-mcp',
	// '@freema/mcp-gsheets',
	// '@WillDent/pipedrive-mcp-server',
	// '@masatoshi118/mcp_google_froms',
	// '@kacase/mcp-outlook',
	// '@jeroensmink98/telegram-mcp',
	// '@jar285/mcp-discord',
	// '@nikolausm/huggingface-mcp-server',
	// '@mcp-postgres-server',
	// '@mcp-mongodb-atlas',
	// '@farhankaz/redis-mcp',
	// '@domdomegg/airtable-mcp-server',
	// '@lkm1developer/google-docs-mcp-server',
	// '@amgadabdelhafez/dbx-mcp-server',
	// '@cosmix/jira-mcp',
	// '@yoda-digital/mcp-gitlab-server',
	// '@v4lheru/trello-mcp-server',
	// '@Dishant27/linkedin-mcp-server',
	// '@Bob-lance/instagram-engagement-mcp',
	// '@stripe/agent-toolkit/tree/main/modelcontextprotocol',
	// '@mumunha/cal_dot_com_mcpserver',
	// '@paypal/agent-toolkit',
	// '@toolprint/mcp-graphql-forge',
	// '@EvalsOne/mcp-connect',
	// '@ifmelate/n8n-workflow-builder-mcp',
	// '@makenotion/notion-mcp-server',
	// '@nspady/google-calendar-mcp',
];
