/**
 * Featured MCP Servers Configuration
 * 
 * Maintained by toolsdk.ai
 * Contains toolsdk.ai's officially recommended featured mcp servers
 */

export default [
  "@kevinwatt/mcp-webhook",
  "@mzxrai/mcp-openai",
  "@freema/mcp-gsheets",
  "@modelcontextprotocol/server-slack",
  "@Tisik79/MCP-Facebook",
  "@lkm1developer/hubspot-mcp-server",
  "@kazuph/mcp-gmail-gas",
  "@tsmztech/mcp-server-salesforce",
  "@amir-bengherbi/shopify-mcp-server",
  "@mattcoatsworth/Klaviyo-MCP-Server-4-15",
  "@alfork/qbconductor-mcp-server",
  "@nspady/google-calendar-mcp",
  "@mattcoatsworth/mailchip-mcp-server",
  "@makenotion/notion-mcp-server",
  "@WillDent/pipedrive-mcp-server",
  "@koundinya/zd-mcp-server",
  "@taazkareem/clickup-mcp-server",
  "@pnizer/wweb-mcp",
  "@isaacphi/mcp-gdrive",
  "@masatoshi118/mcp_google_froms",
  "@kacase/mcp-outlook",
  "@jeroensmink98/telegram-mcp",
  "@jar285/mcp-discord",
  "@floriscornel/teams-mcp",
  "@pinkpixel/mindbridge",
  "@nikolausm/huggingface-mcp-server",
  "@mcp-postgres-server",
  "@kevinwatt/mysql-mcp",
  "@mcp-mongodb-atlas",
  "@farhankaz/redis-mcp",
  "@domdomegg/airtable-mcp-server",
  "@lkm1developer/google-docs-mcp-server",
  "@amgadabdelhafez/dbx-mcp-server",
  "@cosmix/jira-mcp",
  "@modelcontextprotocol/server-github",
  "@yoda-digital/mcp-gitlab-server",
  "@v4lheru/trello-mcp-server",
  "@cristip73/mcp-server-asana",
  "@Dishant27/linkedin-mcp-server",
  "@enescinar/twitter-mcp",
  "@Bob-lance/instagram-engagement-mcp",
  "@stripe/agent-toolkit/tree/main/modelcontextprotocol",
  "@paypal/agent-toolkit",
  "@toolsdk.ai/mcp-server-google-analytics",
  "@mumunha/cal_dot_com_mcpserver",
  "@toolprint/mcp-graphql-forge",
  "@EvalsOne/mcp-connect",
  "@ifmelate/n8n-workflow-builder-mcp"
];
